import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk

def main(app):
    win = Gtk.ApplicationWindow(application=app)
    win.set_title('Calculator')
    win.set_size_request(300, 400)

    container = Gtk.Box(spacing=16, margin_bottom=16, margin_top=16, margin_start=32, margin_end=32, orientation=Gtk.Orientation.VERTICAL)

    display = Gtk.Entry(editable=False)


    def add_to_display(button):
        display.get_buffer().set_text(display.get_buffer().get_text() + button.get_label().replace('%', '/100').replace('x', '*'), -1)

    def calculate(button):
        expr = display.get_buffer().get_text()
        result = eval(expr)
        if isinstance(result, float) and result.is_integer():
            result = str(int(result))
        else:
            result = str(result)
        display.get_buffer().set_text(result, -1)

    def clear(button):
        expr = display.get_buffer().get_text()
        display.get_buffer().set_text(expr[:-1:], -1)

    def clear_all(button):
        display.get_buffer().set_text('', -1)


    nums = Gtk.Grid(row_spacing=4, column_spacing=4)
    num1 = Gtk.Button(label='1')
    num2 = Gtk.Button(label='2')
    num3 = Gtk.Button(label='3')

    num4 = Gtk.Button(label='4')
    num5 = Gtk.Button(label='5')
    num6 = Gtk.Button(label='6')

    num7 = Gtk.Button(label='7')
    num8 = Gtk.Button(label='8')
    num9 = Gtk.Button(label='9')

    num0 = Gtk.Button(label='0')
    num00 = Gtk.Button(label='00')
    dot = Gtk.Button(label='.')

    plus = Gtk.Button(label='+')
    minus = Gtk.Button(label='-')
    multi = Gtk.Button(label='x')
    divide = Gtk.Button(label='/')
    equal = Gtk.Button(label='=')
    perc = Gtk.Button(label='%')

    C = Gtk.Button(label='C')
    CE = Gtk.Button(label='CE')

    num1.set_hexpand(True)
    num1.set_vexpand(True)
    num2.set_hexpand(True)
    num2.set_vexpand(True)
    num3.set_hexpand(True)
    num3.set_vexpand(True)
    num4.set_hexpand(True)
    num4.set_vexpand(True)
    num5.set_hexpand(True)
    num5.set_vexpand(True)
    num6.set_hexpand(True)
    num6.set_vexpand(True)
    num7.set_hexpand(True)
    num7.set_vexpand(True)
    num8.set_hexpand(True)
    num8.set_vexpand(True)
    num9.set_hexpand(True)
    num9.set_vexpand(True)
    num0.set_hexpand(True)
    num0.set_vexpand(True)
    num00.set_hexpand(True)
    num00.set_vexpand(True)
    dot.set_hexpand(True)
    dot.set_vexpand(True)
    plus.set_hexpand(True)
    plus.set_vexpand(True)
    minus.set_hexpand(True)
    minus.set_vexpand(True)
    multi.set_hexpand(True)
    multi.set_vexpand(True)
    divide.set_hexpand(True)
    divide.set_vexpand(True)
    equal.set_hexpand(True)
    equal.set_vexpand(True)
    perc.set_hexpand(True)
    perc.set_vexpand(True)
    C.set_hexpand(True)
    C.set_vexpand(True)
    CE.set_hexpand(True)
    CE.set_vexpand(True)

    num1.connect('clicked', add_to_display)
    num2.connect('clicked', add_to_display)
    num3.connect('clicked', add_to_display)
    num4.connect('clicked', add_to_display)
    num5.connect('clicked', add_to_display)
    num6.connect('clicked', add_to_display)
    num7.connect('clicked', add_to_display)
    num8.connect('clicked', add_to_display)
    num9.connect('clicked', add_to_display)
    num0.connect('clicked', add_to_display)
    num00.connect('clicked', add_to_display)
    dot.connect('clicked', add_to_display)
    plus.connect('clicked', add_to_display)
    minus.connect('clicked', add_to_display)
    divide.connect('clicked', add_to_display)
    multi.connect('clicked', add_to_display)
    perc.connect('clicked', add_to_display)
    equal.connect('clicked', calculate)
    C.connect('clicked', clear)
    CE.connect('clicked', clear_all)

    nums.attach(C, 1, 0, 1, 1)
    nums.attach(CE, 2, 0, 1, 1)
    nums.attach(perc, 3, 0, 1, 1)
    nums.attach(num1, 1, 1, 1, 1)
    nums.attach(num2, 2, 1, 1, 1)
    nums.attach(num3, 3, 1, 1, 1)
    nums.attach(plus, 4, 0, 1, 1)
    nums.attach(num4, 1, 2, 1, 1)
    nums.attach(num5, 2, 2, 1, 1)
    nums.attach(num6, 3, 2, 1, 1)
    nums.attach(minus, 4, 1, 1, 1)
    nums.attach(num7, 1, 3, 1, 1)
    nums.attach(num8, 2, 3, 1, 1)
    nums.attach(num9, 3, 3, 1, 1)
    nums.attach(multi, 4, 2, 1, 1)
    nums.attach(num0, 1, 4, 1, 1)
    nums.attach(num00, 2, 4, 1, 1)
    nums.attach(dot, 3, 4, 1, 1)
    nums.attach(equal, 4, 4, 1, 1)
    nums.attach(divide, 4, 3, 1, 1)
    container.append(display)
    container.append(nums)
    win.set_child(container)
    win.present()

app = Gtk.Application(application_id='test.gtk.Calculator')
app.connect('activate', main)
app.run(None)